### ISSUE TITLE
Experimental decorators?

### ISSUE THREAD

**Issue by jasonhjohnson** [ts-engine/ts-engine#106]
Hi,

How would I enable support for experimental decorators?

Thanks,
Jason

**Comment by LeeCheneler** [comment]
Hey! Good question!

There actually isn't a way right now! tsconfig is actually pretty much the single piece of configuration you can't override right now!! This is more a hangover from a previous internal implementation that actually meant I couldn't allow it to be overridden, however that restriction doesn't exist anymore so I could add support for this now.

Not supporting experimental decorators is somewhat of an oversight on my part. I don't write TypeScript that utilises them as they're experimental. It is reasonable to support them out the box though as popular packages like Angular rely on them heavily anyway.

We don't have anything major planned for the next release right now as ts-engine is currently running like a dream on the few internal projects we're using it on.

What I'll do though is get a minor release out this week or next with experimental decorators supported out the box 😄

**Comment by LeeCheneler** [comment]
Hmm, I'll need to do a little reading up before I do enable it by default. Just dumping some reading here, ts-engine typechecks with tsc but builds using rollup and babel. Differences in decorator APIs might be a potential issue. If not then this addition is a no brainer.

https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options
https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by LeeCheneler** [comment]
this is now merged into master @jasonhjohnson, expect it in the next release 👍
