### ISSUE TITLE
Better feedback about why a given name is invalid

### ISSUE THREAD

**Issue by JamesZoft** [ts-engine/ts-engine#108]
At the moment ts-engine only allows package names with whatever npm's valid package naming system is. ts-engine says:

`<name> is not a valid npm package name`

Some better feedback would be good to resolve this - perhaps giving guidelines on what the system is, linking to the system or simply giving common pitfalls like "only snake case, no camelCase or PascalCase"

Cheers!

**Comment by LeeCheneler** [comment]
This is merged into master now, expect it in the next release
