### ISSUE TITLE
Feature request: ability to run `new-package` from a different working dir

### ISSUE THREAD

**Issue by James-Reed-cognito** [ts-engine/ts-engine#118]
Similar to how you can run things like node's child_process' `spawn` from another directory by passing `cwd: <some-dir>` it would be good to be able to run `new-package` from a different dir. Consider this example:
```
/
  package.json
  components/
    /foo
    /bar
```
where I have installed @ts-engine/cli as a dev dependency at the root package.json for ease of use. It would be good to be able to make a new package in `components` without having to `cd` first. Something simple like adding `--working-dir components` would be enough.

Cheers!

**Comment by LeeCheneler** [comment]
The new package command has been removed in v2. Contemplating template support in future.
