### ISSUE TITLE
Warning when creating new package using ts-engine

### ISSUE THREAD

**Issue by James-Reed-cognito** [ts-engine/ts-engine#120]
When creating a new package and installing dependencies, this message appears:

```warning @ts-engine/cli > rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.```

It doesn't seem to have any immediate issue with how ts-engine works, but I figured it was worth raising an issue for to track. :)

**Comment by LeeCheneler** [comment]
Duplicate of #114
