### ISSUE TITLE
Allow configuration of entry and destination

### ISSUE THREAD

**Issue by joeyfigaro** [ts-engine/ts-engine#125]
https://github.com/ts-engine/ts-engine/blob/3247ebc2ddf8a1d8d97718ee04fed1392398ad23/packages/cli/src/constants.ts#L1-L14

Not all of my libraries *need* a src directory. It'd be great if we could configure this via CLI.

**Comment by LeeCheneler** [comment]
Hey, yeah so in November I did a bunch of work on v2 and as part of that all the commands now take in 1 or more file paths or globs for input files and then the output are matched in the dist file, so for instance:

```sh
# outputs dist/index.js, dist/utils.js, dist/react/index.js
ts-engine build src/index.ts src/utils.ts src/react/index.ts
```

v2 isn't quite ready for release yet as there are a few things to finish up and development has slowed the last few weeks but I'll be back on it soon!

**Comment by joeyfigaro** [comment]
@LeeCheneler Beautiful, man. Looking forward to checking it out :)

**Comment by LeeCheneler** [comment]
V2 beta will be released very shortly! Here is a sneak peak at the docs. See how you can now provide one or more files to build and their destination in 'dist/' matches their directory structure in 'src/' 🙂

https://hopeful-ptolemy-4c0c65.netlify.app/docs/building-your-code

**Comment by LeeCheneler** [comment]
V2 beta is released now 🙌 check out the updated docs at https://ts-engine.dev
