### ISSUE TITLE
When running a build with `--emit-types` things can conflict with Jest types.

### ISSUE THREAD

**Issue by tom-drake** [ts-engine/ts-engine#148]
I have a basic setup with:
```js
function describe(): void {
  return
}
```

and when I run `tse build --emit-types --output esm src/index.ts` I'm seeing a conflict with the Jest types as in the following screenshot.
![Screenshot from 2021-01-31 02-40-39](https://user-images.githubusercontent.com/23510700/106373077-ffda1700-636d-11eb-85a4-ca718eab6c18.png)

I think its is probably more of a TypeScript thing due to Jest declaring these globally and it conflicting. Not sure it should conflict during a build though. Thoughts?

**Comment by LeeCheneler** [comment]
hmm, I'll look into this as I thought types were only applied globally in `.test/.spec` files

**Comment by LeeCheneler** [comment]
Yeah so this a typescript thing, when the jest types are installed it defines describe globally.

Can't really do much about this. Not sure removing the jest file from the type def files during a build is a good idea. It wouldn't work for packages that are using jest in their build, for instance building a jest centric library for testing.

I'm going to close this for now.
