### ISSUE TITLE
Errors with `new-package` command

### ISSUE THREAD

**Issue by cncshaggy** [ts-engine/ts-engine#53]
I think I found a bug, because here is what happened
```
C:\Users\cncshaggy\AppData\Local\Temp>npm i -g @ts-engine/cli
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
...
+ @ts-engine/cli@1.5.0
added 1020 packages from 520 contributors in 34.699s

C:\Users\cncshaggy\AppData\Local\Temp>ts-engine new-package --node-app --name @examples/node-app
(node:20388) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at C:\Users\cncshaggy\AppData\Roaming\npm\node_modules\@ts-engine\cli\dist\commands\new-package.js:117:142
    at step (C:\Users\cncshaggy\AppData\Roaming\npm\node_modules\@ts-engine\cli\dist\commands\new-package.js:33:23)
    at Object.next (C:\Users\cncshaggy\AppData\Roaming\npm\node_modules\@ts-engine\cli\dist\commands\new-package.js:14:53)
    at fulfilled (C:\Users\cncshaggy\AppData\Roaming\npm\node_modules\@ts-engine\cli\dist\commands\new-package.js:5:58)

C:\Users\cncshaggy\AppData\Local\Temp>node -v
v13.9.0
```

**Comment by LeeCheneler** [comment]
Hey thanks for your contribution! It looks like you're running Windows! I must admit I'm a Mac user and haven't tested this on Windows yet 😬 

I've got access to Windows though so I'll be sure to do some testing on Windows. Looking at GH Actions virtual runners it looks like they do support Windows Server 2019 so I'll look into getting the verification pipeline running on Windows too.

Watch this space 👍

**Comment by kevinkhill** [comment]
I ran the exact same commands, and got this...
![Screenshot_2020-05-18-15-27-45](https://user-images.githubusercontent.com/266076/82265621-48ef5580-991c-11ea-9881-11487cf64332.png)

**Comment by LeeCheneler** [comment]
what version is installed globally? when you run `ts-engine --version`

**Comment by LeeCheneler** [comment]
@kevinkhill you ran `ts-engine new-project ...` instead of `ts-engine new-package...` 😅 easy mistake to make!

**Comment by kevinkhill** [comment]
:rofl: oh wow! (I sometimes have trouble debugging my own work because of seeing words wrong like this)

Whoops!

Food for thought.... Alias the two? or shorten it to just `new` or `create`?

**Comment by LeeCheneler** [comment]
possibly, feel free to make an issue with the label "enhancement" for a feature request

**Comment by LeeCheneler** [comment]
I've replicated this issue on a windows VM now and will start looking into the fix

**Comment by LeeCheneler** [comment]
I'll have a fix out for this today, the PR is just processing now, I've also created an issue to run the e2e tests on windows as well as just linux https://github.com/ts-engine/ts-engine/issues/55 (not sure if there are cost implications for that though I need to look into it)

**Comment by LeeCheneler** [comment]
All done 
![image](https://user-images.githubusercontent.com/14389381/82327459-59fc9d00-99d6-11ea-9f83-29900c6289f2.png)
